name: tests

on: [push, pull_request]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
        ports: ['3306:3306']
        options: >-
          --health-cmd="mysqladmin ping -h localhost -ppassword"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo, pdo_mysql
          coverage: none

      - name: Composer install
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Prepare env (MySQL)
        run: |
          cp .env.example .env
          cp .env.testing.example .env.testing || true
          php artisan key:generate
          php -r "copy('.env.testing','.env.testing.bak');"
          sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=mysql/' .env.testing
          sed -i 's/DB_HOST=.*/DB_HOST=127.0.0.1/' .env.testing
          sed -i 's/DB_PORT=.*/DB_PORT=3306/' .env.testing
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=testing/' .env.testing
          sed -i 's/DB_USERNAME=.*/DB_USERNAME=root/' .env.testing
          sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=password/' .env.testing

      - name: Migrate (testing)
        run: php artisan migrate --env=testing

      - name: Run tests
        run: php artisan test
