name: tests

on: [push, pull_request]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    services: {}
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Prepare env (SQLite)
        run: |
          cp .env.example .env
          php -r "file_exists('.env.testing') || copy('.env.example','.env.testing');"
          sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=sqlite/' .env.testing
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=:memory:/' .env.testing
          php artisan key:generate

      - name: Run tests
        run: php artisan test
